inherit_from:
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/.rubocop.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/new_defaults.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/performance.yml
  - https://gist.githubusercontent.com/pat/ba3b8ffb1901bfe5439b460943b6b019/raw/rails.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/bundle'
    - 'bin/setup'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*_spec.rb'
