default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% unless ENV.key?('DATABASE_URL') %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  <% end %>

development:
  <<: *default
  database: support_act_development

test:
  <<: *default
  <% if ENV.key?('DATABASE_URL') %>
  url: <%= ENV.fetch('DATABASE_URL') %>
  <% else %>
  database: support_act_test
  <% end %>

production:
  url: <%= ENV.fetch('DATABASE_URL', '') %>
